version: '2'
services:
    web:
      restart: always
      build: .
      entrypoint: /permanode/scripts/permanode_web.sh
      ports:
        - "9080:9080"
      volumes:
        - .:/permanode
    cassandra:
      image: cassandra:2.2.8
      hostname: cassandra
      ports:
        - 9042:9042
      volumes:
        - /var/lib/cassandra:/var/lib/cassandra
